version: 0.2

env:
  variables:
    DIRECTORY: .\test

phases:
  build:
    commands:
      - |
        $env:DIRECTORY
        $env:Path
        $env:Path = "C:\tools\cygwin\bin;$env:Path"
        $env:Path
        $env:CODEBUILD_SRC_DIR
        
