--- 
env: 
  variables: 
    DIRECTORY: .\test
    VALUE1: test
    VALUE2: test2
phases: 
  build: 
    commands: 
      - |
          ls
          pwd
          $env:DIRECTORY
          $env:CODEBUILD_SRC_DIR
          cmd -/c call test.bat $env:VALUE1 $env:CODEBUILD_SRC_DIR

version: 0.2
